name: Docker

on:
  push:
    branches:
    - develop
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --unshallow
    - name: Build & Push latest version
      run: |
        $DEVELOP_BRANCH=develop
        git reset --hard $DEVELOP_BRANCH
        git status
        docker build -t nwtgck/piping-server:$DEVELOP_BRANCH .
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u nwtgck --password-stdin
        docker push nwtgck/piping-server:$DEVELOP_BRANCH
